// ============================================
// ## file THIS FILE IS AUTO-GENERATED BY BLUEPRINT
// ?? Blueprint : iam.blueprint.json
// !! If this comment is removed, blueprint engine WILL NOT override this file.
// ============================================



import { User } from "app/models";

export default async function UserSeeder() {
    // =========================>
    // ## Seed the application's database
    // =========================>
    
    await User.query().insert([
        {"name": "Admin", "email": "admin@mail.com", "password": "$2b$10$tPX5QhnM.vUEDmDpht6O4OarVyTh43NTxhkzFrNxfRijJ3uhSHcli", "image": null, "email_verification_at": "0001-01-01 01:01:01.000+00"},
      {"name": "User", "email": "user@mail.com", "password": "$2b$10$tPX5QhnM.vUEDmDpht6O4OarVyTh43NTxhkzFrNxfRijJ3uhSHcli", "image": null, "email_verification_at": "0001-01-01 01:01:01.000+00"}
    ]);
}
